<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Lodestar.Loader</AssemblyName>
    <RootNamespace>Lodestar.Loader</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets/Lodestar.ico</ApplicationIcon>
    <Version>3.0.0</Version>
    <AssemblyVersion>3.0.0.0</AssemblyVersion>
    <FileVersion>3.0.0.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="System.IO" />
    <Resource Include="Assets/Lodestar.ico" />
  </ItemGroup>
</Project>
